name: Cloudflare Pages e2e specs
on: [pull_request]
jobs:
  cloudflare_pages:
    runs-on: ubuntu-latest
    # Allow GITHUB_TOKEN to write deployments for my action (https://docs.github.com/en/actions/security-guides/automatic-token-authentication)
#    permissions:
#      contents: read
#      deployments: read
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - name: cf
        uses: WalshyDev/cf-pages-await@v1
        id: cf
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          project: 'pf-web'
#      - run: echo ${{steps.cf.outputs.url}}
      - name: Cypress run baseurl=${{steps.cf.outputs.url}}
        uses: cypress-io/github-action@v5
        with:
          spec: test/cypress/e2e/pollofeed
#          record: true
#          parallel: true
#          browser: chrome
        env:
          CYPRESS_BASE_URL: ${{steps.cf.outputs.url}}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # pass the Cypress Cloud record key as an environment variable
#          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
#          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
